public class Fibonacci
{
	/*public static void generateFib (Integer inputVal)
    {
        List<Integer>fib = new List<Integer>();
        integer first = 0;
        integer second = 1;
        integer next=0;
        integer fin = 0;
        system.debug('Input is '+inputVal);
        for(integer i=0; i<inputVal; i++)
        {
            fib.add(next);
            system.debug(fib);
      		next = first + second;
            first = second;
            second = next;
            
        }
        //debug List
        
    }*/
}